apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
  namespace: httpbin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: nfs