apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
  namespace: httpbin
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.httpbin.svc.cluster.local
    path: "/nfs-share"
  mountOptions:
    - nfsvers=4